spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://plim-db.cger7irvgjwb.ap-northeast-2.rds.amazonaws.com:3306/Plim_DB?characterEncoding=UTF-8&serverTimezone=UTC
      username: admin
      password: plimdbteam
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: mjuplim@gmail.com
    password: plimq1w2e3
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true